# Generated by Django 5.1.7 on 2025-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_accept', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_model',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='image_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image_model',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
